/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UtilizationRouteImport } from './routes/utilization'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as MachineRouteImport } from './routes/machine'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsSnapShotRouteImport } from './routes/settings.snap-shot'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsProjectsRouteImport } from './routes/settings.projects'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects.$projectKey'
import { Route as ConnectCallbackRouteImport } from './routes/connect_.callback'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as SettingsInfinitusIndexRouteImport } from './routes/settings.infinitus.index'
import { Route as SettingsInfinitusThemesRouteImport } from './routes/settings.infinitus.themes'
import { Route as SettingsInfinitusTeamRouteImport } from './routes/settings.infinitus.team'
import { Route as SettingsInfinitusSessionsRouteImport } from './routes/settings.infinitus.sessions'
import { Route as SettingsInfinitusProfilesRouteImport } from './routes/settings.infinitus.profiles'
import { Route as SettingsInfinitusNotificationsRouteImport } from './routes/settings.infinitus.notifications'
import { Route as SettingsInfinitusEnginesRouteImport } from './routes/settings.infinitus.engines'
import { Route as SettingsInfinitusDevicesRouteImport } from './routes/settings.infinitus.devices'
import { Route as SettingsInfinitusAnimationsRouteImport } from './routes/settings.infinitus.animations'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilizationRoute = UtilizationRouteImport.update({
  id: '/utilization',
  path: '/utilization',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineRoute = MachineRouteImport.update({
  id: '/machine',
  path: '/machine',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSnapShotRoute = SettingsSnapShotRouteImport.update({
  id: '/snap-shot',
  path: '/snap-shot',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/projects/$projectKey',
  path: '/projects/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectCallbackRoute = ConnectCallbackRouteImport.update({
  id: '/connect_/callback',
  path: '/connect/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsInfinitusIndexRoute = SettingsInfinitusIndexRouteImport.update({
  id: '/infinitus/',
  path: '/infinitus/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInfinitusThemesRoute = SettingsInfinitusThemesRouteImport.update({
  id: '/infinitus/themes',
  path: '/infinitus/themes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInfinitusTeamRoute = SettingsInfinitusTeamRouteImport.update({
  id: '/infinitus/team',
  path: '/infinitus/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInfinitusSessionsRoute =
  SettingsInfinitusSessionsRouteImport.update({
    id: '/infinitus/sessions',
    path: '/infinitus/sessions',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsInfinitusProfilesRoute =
  SettingsInfinitusProfilesRouteImport.update({
    id: '/infinitus/profiles',
    path: '/infinitus/profiles',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsInfinitusNotificationsRoute =
  SettingsInfinitusNotificationsRouteImport.update({
    id: '/infinitus/notifications',
    path: '/infinitus/notifications',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsInfinitusEnginesRoute =
  SettingsInfinitusEnginesRouteImport.update({
    id: '/infinitus/engines',
    path: '/infinitus/engines',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsInfinitusDevicesRoute =
  SettingsInfinitusDevicesRouteImport.update({
    id: '/infinitus/devices',
    path: '/infinitus/devices',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsInfinitusAnimationsRoute =
  SettingsInfinitusAnimationsRouteImport.update({
    id: '/infinitus/animations',
    path: '/infinitus/animations',
    getParentRoute: () => SettingsRoute,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/machine': typeof MachineRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/utilization': typeof UtilizationRoute
  '/welcome': typeof WelcomeRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/infinitus/animations': typeof SettingsInfinitusAnimationsRoute
  '/settings/infinitus/devices': typeof SettingsInfinitusDevicesRoute
  '/settings/infinitus/engines': typeof SettingsInfinitusEnginesRoute
  '/settings/infinitus/notifications': typeof SettingsInfinitusNotificationsRoute
  '/settings/infinitus/profiles': typeof SettingsInfinitusProfilesRoute
  '/settings/infinitus/sessions': typeof SettingsInfinitusSessionsRoute
  '/settings/infinitus/team': typeof SettingsInfinitusTeamRoute
  '/settings/infinitus/themes': typeof SettingsInfinitusThemesRoute
  '/settings/infinitus/': typeof SettingsInfinitusIndexRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/machine': typeof MachineRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/utilization': typeof UtilizationRoute
  '/welcome': typeof WelcomeRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/infinitus/animations': typeof SettingsInfinitusAnimationsRoute
  '/settings/infinitus/devices': typeof SettingsInfinitusDevicesRoute
  '/settings/infinitus/engines': typeof SettingsInfinitusEnginesRoute
  '/settings/infinitus/notifications': typeof SettingsInfinitusNotificationsRoute
  '/settings/infinitus/profiles': typeof SettingsInfinitusProfilesRoute
  '/settings/infinitus/sessions': typeof SettingsInfinitusSessionsRoute
  '/settings/infinitus/team': typeof SettingsInfinitusTeamRoute
  '/settings/infinitus/themes': typeof SettingsInfinitusThemesRoute
  '/settings/infinitus': typeof SettingsInfinitusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/machine': typeof MachineRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/utilization': typeof UtilizationRoute
  '/welcome': typeof WelcomeRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRoute
  '/connect_/callback': typeof ConnectCallbackRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/infinitus/animations': typeof SettingsInfinitusAnimationsRoute
  '/settings/infinitus/devices': typeof SettingsInfinitusDevicesRoute
  '/settings/infinitus/engines': typeof SettingsInfinitusEnginesRoute
  '/settings/infinitus/notifications': typeof SettingsInfinitusNotificationsRoute
  '/settings/infinitus/profiles': typeof SettingsInfinitusProfilesRoute
  '/settings/infinitus/sessions': typeof SettingsInfinitusSessionsRoute
  '/settings/infinitus/team': typeof SettingsInfinitusTeamRoute
  '/settings/infinitus/themes': typeof SettingsInfinitusThemesRoute
  '/settings/infinitus/': typeof SettingsInfinitusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/activity'
    | '/connect'
    | '/machine'
    | '/pair'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/utilization'
    | '/welcome'
    | '/pull-requests'
    | '/connect/callback'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/infinitus/animations'
    | '/settings/infinitus/devices'
    | '/settings/infinitus/engines'
    | '/settings/infinitus/notifications'
    | '/settings/infinitus/profiles'
    | '/settings/infinitus/sessions'
    | '/settings/infinitus/team'
    | '/settings/infinitus/themes'
    | '/settings/infinitus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/activity'
    | '/connect'
    | '/machine'
    | '/pair'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/utilization'
    | '/welcome'
    | '/pull-requests'
    | '/connect/callback'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/infinitus/animations'
    | '/settings/infinitus/devices'
    | '/settings/infinitus/engines'
    | '/settings/infinitus/notifications'
    | '/settings/infinitus/profiles'
    | '/settings/infinitus/sessions'
    | '/settings/infinitus/team'
    | '/settings/infinitus/themes'
    | '/settings/infinitus'
  id:
    | '__root__'
    | '/_chat'
    | '/accounts'
    | '/activity'
    | '/connect'
    | '/machine'
    | '/pair'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/utilization'
    | '/welcome'
    | '/_chat/pull-requests'
    | '/connect_/callback'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/settings/infinitus/animations'
    | '/settings/infinitus/devices'
    | '/settings/infinitus/engines'
    | '/settings/infinitus/notifications'
    | '/settings/infinitus/profiles'
    | '/settings/infinitus/sessions'
    | '/settings/infinitus/team'
    | '/settings/infinitus/themes'
    | '/settings/infinitus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  ActivityRoute: typeof ActivityRoute
  ConnectRoute: typeof ConnectRoute
  MachineRoute: typeof MachineRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatsRoute: typeof StatsRoute
  UsageRoute: typeof UsageRoute
  UtilizationRoute: typeof UtilizationRoute
  WelcomeRoute: typeof WelcomeRoute
  ConnectCallbackRoute: typeof ConnectCallbackRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilization': {
      id: '/utilization'
      path: '/utilization'
      fullPath: '/utilization'
      preLoaderRoute: typeof UtilizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine': {
      id: '/machine'
      path: '/machine'
      fullPath: '/machine'
      preLoaderRoute: typeof MachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/snap-shot': {
      id: '/settings/snap-shot'
      path: '/snap-shot'
      fullPath: '/settings/snap-shot'
      preLoaderRoute: typeof SettingsSnapShotRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect_/callback': {
      id: '/connect_/callback'
      path: '/connect/callback'
      fullPath: '/connect/callback'
      preLoaderRoute: typeof ConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/infinitus/': {
      id: '/settings/infinitus/'
      path: '/infinitus'
      fullPath: '/settings/infinitus/'
      preLoaderRoute: typeof SettingsInfinitusIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/themes': {
      id: '/settings/infinitus/themes'
      path: '/infinitus/themes'
      fullPath: '/settings/infinitus/themes'
      preLoaderRoute: typeof SettingsInfinitusThemesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/team': {
      id: '/settings/infinitus/team'
      path: '/infinitus/team'
      fullPath: '/settings/infinitus/team'
      preLoaderRoute: typeof SettingsInfinitusTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/sessions': {
      id: '/settings/infinitus/sessions'
      path: '/infinitus/sessions'
      fullPath: '/settings/infinitus/sessions'
      preLoaderRoute: typeof SettingsInfinitusSessionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/profiles': {
      id: '/settings/infinitus/profiles'
      path: '/infinitus/profiles'
      fullPath: '/settings/infinitus/profiles'
      preLoaderRoute: typeof SettingsInfinitusProfilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/notifications': {
      id: '/settings/infinitus/notifications'
      path: '/infinitus/notifications'
      fullPath: '/settings/infinitus/notifications'
      preLoaderRoute: typeof SettingsInfinitusNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/engines': {
      id: '/settings/infinitus/engines'
      path: '/infinitus/engines'
      fullPath: '/settings/infinitus/engines'
      preLoaderRoute: typeof SettingsInfinitusEnginesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/devices': {
      id: '/settings/infinitus/devices'
      path: '/infinitus/devices'
      fullPath: '/settings/infinitus/devices'
      preLoaderRoute: typeof SettingsInfinitusDevicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infinitus/animations': {
      id: '/settings/infinitus/animations'
      path: '/infinitus/animations'
      fullPath: '/settings/infinitus/animations'
      preLoaderRoute: typeof SettingsInfinitusAnimationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatPullRequestsRoute: typeof ChatPullRequestsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatPullRequestsRoute: ChatPullRequestsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSnapShotRoute: typeof SettingsSnapShotRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsInfinitusAnimationsRoute: typeof SettingsInfinitusAnimationsRoute
  SettingsInfinitusDevicesRoute: typeof SettingsInfinitusDevicesRoute
  SettingsInfinitusEnginesRoute: typeof SettingsInfinitusEnginesRoute
  SettingsInfinitusNotificationsRoute: typeof SettingsInfinitusNotificationsRoute
  SettingsInfinitusProfilesRoute: typeof SettingsInfinitusProfilesRoute
  SettingsInfinitusSessionsRoute: typeof SettingsInfinitusSessionsRoute
  SettingsInfinitusTeamRoute: typeof SettingsInfinitusTeamRoute
  SettingsInfinitusThemesRoute: typeof SettingsInfinitusThemesRoute
  SettingsInfinitusIndexRoute: typeof SettingsInfinitusIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSnapShotRoute: SettingsSnapShotRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsInfinitusAnimationsRoute: SettingsInfinitusAnimationsRoute,
  SettingsInfinitusDevicesRoute: SettingsInfinitusDevicesRoute,
  SettingsInfinitusEnginesRoute: SettingsInfinitusEnginesRoute,
  SettingsInfinitusNotificationsRoute: SettingsInfinitusNotificationsRoute,
  SettingsInfinitusProfilesRoute: SettingsInfinitusProfilesRoute,
  SettingsInfinitusSessionsRoute: SettingsInfinitusSessionsRoute,
  SettingsInfinitusTeamRoute: SettingsInfinitusTeamRoute,
  SettingsInfinitusThemesRoute: SettingsInfinitusThemesRoute,
  SettingsInfinitusIndexRoute: SettingsInfinitusIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AccountsRoute: AccountsRoute,
  ActivityRoute: ActivityRoute,
  ConnectRoute: ConnectRoute,
  MachineRoute: MachineRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatsRoute: StatsRoute,
  UsageRoute: UsageRoute,
  UtilizationRoute: UtilizationRoute,
  WelcomeRoute: WelcomeRoute,
  ConnectCallbackRoute: ConnectCallbackRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
