/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UtilizationRouteImport } from './routes/utilization'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsSnapShotRouteImport } from './routes/settings.snap-shot'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsProjectsRouteImport } from './routes/settings.projects'
import { Route as SettingsPriorityRouteImport } from './routes/settings.priority'
import { Route as SettingsOpenSourceLicensesRouteImport } from './routes/settings.open-source-licenses'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsMenuBarRouteImport } from './routes/settings.menu-bar'
import { Route as SettingsLockRouteImport } from './routes/settings.lock'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsEnginesRouteImport } from './routes/settings.engines'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsDevicesRouteImport } from './routes/settings.devices'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAnimationsRouteImport } from './routes/settings.animations'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects.$projectKey'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as SettingsInfinitusSplatRouteImport } from './routes/settings.infinitus.$'
import { Route as SettingsEnginesActivityRouteImport } from './routes/settings.engines_.activity'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilizationRoute = UtilizationRouteImport.update({
  id: '/utilization',
  path: '/utilization',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSnapShotRoute = SettingsSnapShotRouteImport.update({
  id: '/snap-shot',
  path: '/snap-shot',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPriorityRoute = SettingsPriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOpenSourceLicensesRoute =
  SettingsOpenSourceLicensesRouteImport.update({
    id: '/open-source-licenses',
    path: '/open-source-licenses',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMenuBarRoute = SettingsMenuBarRouteImport.update({
  id: '/menu-bar',
  path: '/menu-bar',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLockRoute = SettingsLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEnginesRoute = SettingsEnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAnimationsRoute = SettingsAnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/projects/$projectKey',
  path: '/projects/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsInfinitusSplatRoute = SettingsInfinitusSplatRouteImport.update({
  id: '/infinitus/$',
  path: '/infinitus/$',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEnginesActivityRoute = SettingsEnginesActivityRouteImport.update({
  id: '/engines_/activity',
  path: '/engines/activity',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/accounts': typeof AccountsRoute
  '/connect': typeof ConnectRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/utilization': typeof UtilizationRoute
  '/welcome': typeof WelcomeRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/animations': typeof SettingsAnimationsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/engines': typeof SettingsEnginesRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/lock': typeof SettingsLockRoute
  '/settings/menu-bar': typeof SettingsMenuBarRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/priority': typeof SettingsPriorityRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/team': typeof SettingsTeamRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/engines/activity': typeof SettingsEnginesActivityRoute
  '/settings/infinitus/$': typeof SettingsInfinitusSplatRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AccountsRoute
  '/connect': typeof ConnectRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/utilization': typeof UtilizationRoute
  '/welcome': typeof WelcomeRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/animations': typeof SettingsAnimationsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/engines': typeof SettingsEnginesRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/lock': typeof SettingsLockRoute
  '/settings/menu-bar': typeof SettingsMenuBarRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/priority': typeof SettingsPriorityRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/team': typeof SettingsTeamRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/engines/activity': typeof SettingsEnginesActivityRoute
  '/settings/infinitus/$': typeof SettingsInfinitusSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/connect': typeof ConnectRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/utilization': typeof UtilizationRoute
  '/welcome': typeof WelcomeRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/animations': typeof SettingsAnimationsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/engines': typeof SettingsEnginesRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/lock': typeof SettingsLockRoute
  '/settings/menu-bar': typeof SettingsMenuBarRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/priority': typeof SettingsPriorityRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/team': typeof SettingsTeamRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/engines_/activity': typeof SettingsEnginesActivityRoute
  '/settings/infinitus/$': typeof SettingsInfinitusSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/connect'
    | '/pair'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/utilization'
    | '/welcome'
    | '/pull-requests'
    | '/projects/$projectKey'
    | '/settings/animations'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/devices'
    | '/settings/diagnostics'
    | '/settings/engines'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/lock'
    | '/settings/menu-bar'
    | '/settings/notifications'
    | '/settings/open-source-licenses'
    | '/settings/priority'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/settings/team'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/engines/activity'
    | '/settings/infinitus/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/connect'
    | '/pair'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/utilization'
    | '/welcome'
    | '/pull-requests'
    | '/projects/$projectKey'
    | '/settings/animations'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/devices'
    | '/settings/diagnostics'
    | '/settings/engines'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/lock'
    | '/settings/menu-bar'
    | '/settings/notifications'
    | '/settings/open-source-licenses'
    | '/settings/priority'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/settings/team'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/engines/activity'
    | '/settings/infinitus/$'
  id:
    | '__root__'
    | '/_chat'
    | '/accounts'
    | '/connect'
    | '/pair'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/utilization'
    | '/welcome'
    | '/_chat/pull-requests'
    | '/projects/$projectKey'
    | '/settings/animations'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/devices'
    | '/settings/diagnostics'
    | '/settings/engines'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/lock'
    | '/settings/menu-bar'
    | '/settings/notifications'
    | '/settings/open-source-licenses'
    | '/settings/priority'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/settings/team'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/settings/engines_/activity'
    | '/settings/infinitus/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  ConnectRoute: typeof ConnectRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatsRoute: typeof StatsRoute
  UsageRoute: typeof UsageRoute
  UtilizationRoute: typeof UtilizationRoute
  WelcomeRoute: typeof WelcomeRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilization': {
      id: '/utilization'
      path: '/utilization'
      fullPath: '/utilization'
      preLoaderRoute: typeof UtilizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/snap-shot': {
      id: '/settings/snap-shot'
      path: '/snap-shot'
      fullPath: '/settings/snap-shot'
      preLoaderRoute: typeof SettingsSnapShotRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/priority': {
      id: '/settings/priority'
      path: '/priority'
      fullPath: '/settings/priority'
      preLoaderRoute: typeof SettingsPriorityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/open-source-licenses': {
      id: '/settings/open-source-licenses'
      path: '/open-source-licenses'
      fullPath: '/settings/open-source-licenses'
      preLoaderRoute: typeof SettingsOpenSourceLicensesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/menu-bar': {
      id: '/settings/menu-bar'
      path: '/menu-bar'
      fullPath: '/settings/menu-bar'
      preLoaderRoute: typeof SettingsMenuBarRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/lock': {
      id: '/settings/lock'
      path: '/lock'
      fullPath: '/settings/lock'
      preLoaderRoute: typeof SettingsLockRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/engines': {
      id: '/settings/engines'
      path: '/engines'
      fullPath: '/settings/engines'
      preLoaderRoute: typeof SettingsEnginesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/devices': {
      id: '/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/animations': {
      id: '/settings/animations'
      path: '/animations'
      fullPath: '/settings/animations'
      preLoaderRoute: typeof SettingsAnimationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/infinitus/$': {
      id: '/settings/infinitus/$'
      path: '/infinitus/$'
      fullPath: '/settings/infinitus/$'
      preLoaderRoute: typeof SettingsInfinitusSplatRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/engines_/activity': {
      id: '/settings/engines_/activity'
      path: '/engines/activity'
      fullPath: '/settings/engines/activity'
      preLoaderRoute: typeof SettingsEnginesActivityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatPullRequestsRoute: typeof ChatPullRequestsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatPullRequestsRoute: ChatPullRequestsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAnimationsRoute: typeof SettingsAnimationsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsEnginesRoute: typeof SettingsEnginesRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsLockRoute: typeof SettingsLockRoute
  SettingsMenuBarRoute: typeof SettingsMenuBarRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOpenSourceLicensesRoute: typeof SettingsOpenSourceLicensesRoute
  SettingsPriorityRoute: typeof SettingsPriorityRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSnapShotRoute: typeof SettingsSnapShotRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsEnginesActivityRoute: typeof SettingsEnginesActivityRoute
  SettingsInfinitusSplatRoute: typeof SettingsInfinitusSplatRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAnimationsRoute: SettingsAnimationsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsEnginesRoute: SettingsEnginesRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsLockRoute: SettingsLockRoute,
  SettingsMenuBarRoute: SettingsMenuBarRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOpenSourceLicensesRoute: SettingsOpenSourceLicensesRoute,
  SettingsPriorityRoute: SettingsPriorityRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSnapShotRoute: SettingsSnapShotRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsEnginesActivityRoute: SettingsEnginesActivityRoute,
  SettingsInfinitusSplatRoute: SettingsInfinitusSplatRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AccountsRoute: AccountsRoute,
  ConnectRoute: ConnectRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatsRoute: StatsRoute,
  UsageRoute: UsageRoute,
  UtilizationRoute: UtilizationRoute,
  WelcomeRoute: WelcomeRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
