// Generated by tools/t3ref/gen-tokens.py — do not edit. Inputs: tools/t3ref/upstream (see VERSIONS).
import SwiftUI

public enum T3Theme {
    public struct MobilePalette: Sendable {
        public let backdrop: T3RGBA
        public let border: T3RGBA
        public let borderSubtle: T3RGBA
        public let card: T3RGBA
        public let cardAlt: T3RGBA
        public let cardTranslucent: T3RGBA
        public let chevron: T3RGBA
        public let danger: T3RGBA
        public let dangerBorder: T3RGBA
        public let dangerForeground: T3RGBA
        public let dotSeparator: T3RGBA
        public let drawer: T3RGBA
        public let drawerShadow: T3RGBA
        public let foreground: T3RGBA
        public let foregroundMuted: T3RGBA
        public let foregroundSecondary: T3RGBA
        public let foregroundTertiary: T3RGBA
        public let glassSurface: T3RGBA
        public let glassTint: T3RGBA
        public let header: T3RGBA
        public let headerBorder: T3RGBA
        public let icon: T3RGBA
        public let iconMuted: T3RGBA
        public let iconSubtle: T3RGBA
        public let inlineSkillBackground: T3RGBA
        public let inlineSkillBorder: T3RGBA
        public let inlineSkillForeground: T3RGBA
        public let input: T3RGBA
        public let inputBorder: T3RGBA
        public let mdBlockquoteBg: T3RGBA
        public let mdBlockquoteBorder: T3RGBA
        public let mdBody: T3RGBA
        public let mdCodeBg: T3RGBA
        public let mdCodeText: T3RGBA
        public let mdHr: T3RGBA
        public let mdLink: T3RGBA
        public let mdStrong: T3RGBA
        public let mdUserCodeBg: T3RGBA
        public let mdUserCodeText: T3RGBA
        public let mdUserFenceBg: T3RGBA
        public let mdUserFenceText: T3RGBA
        public let placeholder: T3RGBA
        public let primary: T3RGBA
        public let primaryForeground: T3RGBA
        public let primaryShadow: T3RGBA
        public let screen: T3RGBA
        public let secondary: T3RGBA
        public let secondaryBorder: T3RGBA
        public let secondaryForeground: T3RGBA
        public let separator: T3RGBA
        public let sheet: T3RGBA
        public let sheetSolid: T3RGBA
        public let sidebarSearch: T3RGBA
        public let statusBar: T3RGBA
        public let subtle: T3RGBA
        public let subtleStrong: T3RGBA
        public let switchActiveThumb: T3RGBA
        public let switchActiveTrack: T3RGBA
        public let switchInactiveThumb: T3RGBA
        public let switchInactiveTrack: T3RGBA
        public let userBubble: T3RGBA
        public let userBubbleForeground: T3RGBA
        public let userBubbleForegroundMuted: T3RGBA
        public let userBubbleSkillForeground: T3RGBA
        public let warning: T3RGBA
        public let warningBorder: T3RGBA
        public let warningForeground: T3RGBA
        public let wordmark: T3RGBA
    }
    public static let mobileLight = MobilePalette(
        backdrop: T3RGBA(0, 0, 0, 0.22),
        border: T3RGBA(0, 0, 0, 0.08),
        borderSubtle: T3RGBA(0, 0, 0, 0.06),
        card: T3RGBA(255, 255, 255, 1.0),
        cardAlt: T3RGBA(245, 245, 245, 1.0),
        cardTranslucent: T3RGBA(255, 255, 255, 0.8),
        chevron: T3RGBA(0, 0, 0, 0.2),
        danger: T3RGBA(254, 242, 242, 1.0),
        dangerBorder: T3RGBA(239, 68, 68, 0.12),
        dangerForeground: T3RGBA(220, 38, 38, 1.0),
        dotSeparator: T3RGBA(0, 0, 0, 0.2),
        drawer: T3RGBA(255, 255, 255, 0.99),
        drawerShadow: T3RGBA(0, 0, 0, 0.12),
        foreground: T3RGBA(38, 38, 38, 1.0),
        foregroundMuted: T3RGBA(115, 115, 115, 1.0),
        foregroundSecondary: T3RGBA(82, 82, 82, 1.0),
        foregroundTertiary: T3RGBA(142, 142, 147, 1.0),
        glassSurface: T3RGBA(255, 255, 255, 0.72),
        glassTint: T3RGBA(255, 255, 255, 0.18),
        header: T3RGBA(255, 255, 255, 0.97),
        headerBorder: T3RGBA(0, 0, 0, 0.06),
        icon: T3RGBA(38, 38, 38, 1.0),
        iconMuted: T3RGBA(82, 82, 82, 1.0),
        iconSubtle: T3RGBA(163, 163, 163, 1.0),
        inlineSkillBackground: T3RGBA(217, 70, 239, 0.12),
        inlineSkillBorder: T3RGBA(217, 70, 239, 0.25),
        inlineSkillForeground: T3RGBA(162, 28, 175, 1.0),
        input: T3RGBA(255, 255, 255, 1.0),
        inputBorder: T3RGBA(0, 0, 0, 0.1),
        mdBlockquoteBg: T3RGBA(0, 0, 0, 0.02),
        mdBlockquoteBorder: T3RGBA(0, 0, 0, 0.08),
        mdBody: T3RGBA(17, 17, 17, 1.0),
        mdCodeBg: T3RGBA(0, 0, 0, 0.04),
        mdCodeText: T3RGBA(38, 38, 38, 1.0),
        mdHr: T3RGBA(0, 0, 0, 0.08),
        mdLink: T3RGBA(37, 99, 235, 1.0),
        mdStrong: T3RGBA(0, 0, 0, 1.0),
        mdUserCodeBg: T3RGBA(255, 255, 255, 0.22),
        mdUserCodeText: T3RGBA(255, 255, 255, 1.0),
        mdUserFenceBg: T3RGBA(0, 0, 0, 0.16),
        mdUserFenceText: T3RGBA(255, 255, 255, 1.0),
        placeholder: T3RGBA(115, 115, 115, 1.0),
        primary: T3RGBA(38, 38, 38, 1.0),
        primaryForeground: T3RGBA(255, 255, 255, 1.0),
        primaryShadow: T3RGBA(0, 0, 0, 1.0),
        screen: T3RGBA(242, 242, 247, 1.0),
        secondary: T3RGBA(255, 255, 255, 1.0),
        secondaryBorder: T3RGBA(0, 0, 0, 0.08),
        secondaryForeground: T3RGBA(38, 38, 38, 1.0),
        separator: T3RGBA(0, 0, 0, 0.04),
        sheet: T3RGBA(242, 242, 247, 0.98),
        sheetSolid: T3RGBA(242, 242, 247, 1.0),
        sidebarSearch: T3RGBA(118, 118, 128, 0.12),
        statusBar: T3RGBA(242, 242, 247, 1.0),
        subtle: T3RGBA(0, 0, 0, 0.04),
        subtleStrong: T3RGBA(0, 0, 0, 0.08),
        switchActiveThumb: T3RGBA(255, 255, 255, 1.0),
        switchActiveTrack: T3RGBA(52, 199, 89, 1.0),
        switchInactiveThumb: T3RGBA(142, 142, 147, 1.0),
        switchInactiveTrack: T3RGBA(0, 0, 0, 0.08),
        userBubble: T3RGBA(0, 122, 255, 1.0),
        userBubbleForeground: T3RGBA(255, 255, 255, 1.0),
        userBubbleForegroundMuted: T3RGBA(255, 255, 255, 0.78),
        userBubbleSkillForeground: T3RGBA(240, 171, 252, 1.0),
        warning: T3RGBA(255, 251, 235, 1.0),
        warningBorder: T3RGBA(253, 230, 138, 1.0),
        warningForeground: T3RGBA(180, 83, 9, 1.0),
        wordmark: T3RGBA(38, 38, 38, 1.0)
    )
    public static let mobileDark = MobilePalette(
        backdrop: T3RGBA(0, 0, 0, 0.48),
        border: T3RGBA(255, 255, 255, 0.06),
        borderSubtle: T3RGBA(255, 255, 255, 0.04),
        card: T3RGBA(23, 23, 23, 1.0),
        cardAlt: T3RGBA(28, 28, 28, 1.0),
        cardTranslucent: T3RGBA(17, 17, 17, 0.8),
        chevron: T3RGBA(255, 255, 255, 0.2),
        danger: T3RGBA(239, 68, 68, 0.14),
        dangerBorder: T3RGBA(248, 113, 113, 0.18),
        dangerForeground: T3RGBA(252, 165, 165, 1.0),
        dotSeparator: T3RGBA(255, 255, 255, 0.2),
        drawer: T3RGBA(14, 14, 14, 0.99),
        drawerShadow: T3RGBA(0, 0, 0, 0.32),
        foreground: T3RGBA(245, 245, 245, 1.0),
        foregroundMuted: T3RGBA(142, 142, 147, 1.0),
        foregroundSecondary: T3RGBA(163, 163, 163, 1.0),
        foregroundTertiary: T3RGBA(99, 99, 102, 1.0),
        glassSurface: T3RGBA(23, 23, 23, 0.78),
        glassTint: T3RGBA(23, 23, 23, 0.24),
        header: T3RGBA(10, 10, 10, 0.97),
        headerBorder: T3RGBA(255, 255, 255, 0.06),
        icon: T3RGBA(245, 245, 245, 1.0),
        iconMuted: T3RGBA(163, 163, 163, 1.0),
        iconSubtle: T3RGBA(142, 142, 147, 1.0),
        inlineSkillBackground: T3RGBA(217, 70, 239, 0.12),
        inlineSkillBorder: T3RGBA(217, 70, 239, 0.25),
        inlineSkillForeground: T3RGBA(240, 171, 252, 1.0),
        input: T3RGBA(20, 20, 20, 1.0),
        inputBorder: T3RGBA(255, 255, 255, 0.08),
        mdBlockquoteBg: T3RGBA(255, 255, 255, 0.03),
        mdBlockquoteBorder: T3RGBA(255, 255, 255, 0.1),
        mdBody: T3RGBA(229, 229, 229, 1.0),
        mdCodeBg: T3RGBA(255, 255, 255, 0.06),
        mdCodeText: T3RGBA(229, 229, 229, 1.0),
        mdHr: T3RGBA(255, 255, 255, 0.08),
        mdLink: T3RGBA(96, 165, 250, 1.0),
        mdStrong: T3RGBA(245, 245, 245, 1.0),
        mdUserCodeBg: T3RGBA(255, 255, 255, 0.18),
        mdUserCodeText: T3RGBA(255, 255, 255, 1.0),
        mdUserFenceBg: T3RGBA(0, 0, 0, 0.28),
        mdUserFenceText: T3RGBA(255, 255, 255, 1.0),
        placeholder: T3RGBA(142, 142, 147, 1.0),
        primary: T3RGBA(245, 245, 245, 1.0),
        primaryForeground: T3RGBA(10, 10, 10, 1.0),
        primaryShadow: T3RGBA(0, 0, 0, 1.0),
        screen: T3RGBA(10, 10, 10, 1.0),
        secondary: T3RGBA(255, 255, 255, 0.04),
        secondaryBorder: T3RGBA(255, 255, 255, 0.06),
        secondaryForeground: T3RGBA(245, 245, 245, 1.0),
        separator: T3RGBA(255, 255, 255, 0.03),
        sheet: T3RGBA(14, 14, 14, 0.98),
        sheetSolid: T3RGBA(14, 14, 14, 1.0),
        sidebarSearch: T3RGBA(118, 118, 128, 0.24),
        statusBar: T3RGBA(10, 10, 10, 1.0),
        subtle: T3RGBA(255, 255, 255, 0.04),
        subtleStrong: T3RGBA(255, 255, 255, 0.08),
        switchActiveThumb: T3RGBA(255, 255, 255, 1.0),
        switchActiveTrack: T3RGBA(48, 209, 88, 1.0),
        switchInactiveThumb: T3RGBA(142, 142, 147, 1.0),
        switchInactiveTrack: T3RGBA(255, 255, 255, 0.06),
        userBubble: T3RGBA(10, 132, 255, 1.0),
        userBubbleForeground: T3RGBA(255, 255, 255, 1.0),
        userBubbleForegroundMuted: T3RGBA(255, 255, 255, 0.78),
        userBubbleSkillForeground: T3RGBA(240, 171, 252, 1.0),
        warning: T3RGBA(69, 26, 3, 0.4),
        warningBorder: T3RGBA(120, 53, 15, 0.6),
        warningForeground: T3RGBA(252, 211, 77, 1.0),
        wordmark: T3RGBA(245, 245, 245, 1.0)
    )
    public struct WebPalette: Sendable {
        public let accent: T3RGBA
        public let accentForeground: T3RGBA
        public let appChromeBackground: T3RGBA
        public let background: T3RGBA
        public let border: T3RGBA
        public let card: T3RGBA
        public let cardForeground: T3RGBA
        public let codeBackground: T3RGBA
        public let codeForeground: T3RGBA
        public let destructive: T3RGBA
        public let destructiveForeground: T3RGBA
        public let error: T3RGBA
        public let errorForeground: T3RGBA
        public let errorSurface: T3RGBA
        public let foreground: T3RGBA
        public let iconMuted: T3RGBA
        public let info: T3RGBA
        public let infoForeground: T3RGBA
        public let input: T3RGBA
        public let messageAction: T3RGBA
        public let messageActionForeground: T3RGBA
        public let messageActionHover: T3RGBA
        public let messageForeground: T3RGBA
        public let messageSurface: T3RGBA
        public let muted: T3RGBA
        public let mutedForeground: T3RGBA
        public let placeholder: T3RGBA
        public let popover: T3RGBA
        public let popoverForeground: T3RGBA
        public let primary: T3RGBA
        public let primaryForeground: T3RGBA
        public let ring: T3RGBA
        public let secondary: T3RGBA
        public let secondaryForeground: T3RGBA
        public let secondaryLabel: T3RGBA
        public let sidebar: T3RGBA
        public let sidebarBorder: T3RGBA
        public let sidebarControlSurface: T3RGBA
        public let sidebarForeground: T3RGBA
        public let sidebarMutedForeground: T3RGBA
        public let sidebarRowActive: T3RGBA
        public let sidebarRowHover: T3RGBA
        public let sidebarRowSelected: T3RGBA
        public let sidebarStageFade: T3RGBA
        public let success: T3RGBA
        public let successForeground: T3RGBA
        public let surfaceRaised: T3RGBA
        public let terminalBackground: T3RGBA
        public let terminalCursor: T3RGBA
        public let terminalForeground: T3RGBA
        public let terminalSelectionBackground: T3RGBA
        public let toolErrorIcon: T3RGBA
        public let toolbarBackground: T3RGBA
        public let toolbarBorder: T3RGBA
        public let toolbarControl: T3RGBA
        public let toolbarControlForeground: T3RGBA
        public let toolbarControlHover: T3RGBA
        public let toolbarForeground: T3RGBA
        public let update: T3RGBA
        public let updateForeground: T3RGBA
        public let updateSurface: T3RGBA
        public let warning: T3RGBA
        public let warningForeground: T3RGBA
        public let warningSurface: T3RGBA
    }
    public static let webLight = WebPalette(
        accent: T3RGBA(244, 244, 245, 1.0),
        accentForeground: T3RGBA(24, 24, 27, 1.0),
        appChromeBackground: T3RGBA(252, 252, 252, 1.0),
        background: T3RGBA(252, 252, 252, 1.0),
        border: T3RGBA(228, 228, 231, 1.0),
        card: T3RGBA(255, 255, 255, 1.0),
        cardForeground: T3RGBA(39, 39, 42, 1.0),
        codeBackground: T3RGBA(255, 255, 255, 1.0),
        codeForeground: T3RGBA(39, 39, 42, 1.0),
        destructive: T3RGBA(251, 44, 54, 1.0),
        destructiveForeground: T3RGBA(193, 0, 7, 1.0),
        error: T3RGBA(251, 44, 54, 1.0),
        errorForeground: T3RGBA(193, 0, 7, 1.0),
        errorSurface: T3RGBA(251, 44, 54, 0.08),
        foreground: T3RGBA(39, 39, 42, 1.0),
        iconMuted: T3RGBA(113, 113, 123, 1.0),
        info: T3RGBA(43, 127, 255, 1.0),
        infoForeground: T3RGBA(20, 71, 230, 1.0),
        input: T3RGBA(212, 212, 216, 1.0),
        messageAction: T3RGBA(27, 78, 216, 1.0),
        messageActionForeground: T3RGBA(255, 255, 255, 1.0),
        messageActionHover: T3RGBA(49, 96, 219, 1.0),
        messageForeground: T3RGBA(39, 39, 42, 1.0),
        messageSurface: T3RGBA(244, 244, 245, 1.0),
        muted: T3RGBA(250, 250, 250, 1.0),
        mutedForeground: T3RGBA(113, 113, 123, 1.0),
        placeholder: T3RGBA(113, 113, 123, 1.0),
        popover: T3RGBA(255, 255, 255, 1.0),
        popoverForeground: T3RGBA(39, 39, 42, 1.0),
        primary: T3RGBA(27, 78, 216, 1.0),
        primaryForeground: T3RGBA(255, 255, 255, 1.0),
        ring: T3RGBA(27, 78, 216, 1.0),
        secondary: T3RGBA(250, 250, 250, 1.0),
        secondaryForeground: T3RGBA(39, 39, 42, 1.0),
        secondaryLabel: T3RGBA(113, 113, 123, 1.0),
        sidebar: T3RGBA(250, 250, 250, 1.0),
        sidebarBorder: T3RGBA(228, 228, 231, 1.0),
        sidebarControlSurface: T3RGBA(244, 244, 245, 1.0),
        sidebarForeground: T3RGBA(39, 39, 42, 1.0),
        sidebarMutedForeground: T3RGBA(113, 113, 123, 1.0),
        sidebarRowActive: T3RGBA(255, 255, 255, 1.0),
        sidebarRowHover: T3RGBA(252, 252, 252, 1.0),
        sidebarRowSelected: T3RGBA(255, 255, 255, 1.0),
        sidebarStageFade: T3RGBA(250, 250, 250, 1.0),
        success: T3RGBA(0, 188, 125, 1.0),
        successForeground: T3RGBA(0, 122, 85, 1.0),
        surfaceRaised: T3RGBA(255, 255, 255, 0.2),
        terminalBackground: T3RGBA(252, 252, 252, 1.0),
        terminalCursor: T3RGBA(38, 56, 78, 1.0),
        terminalForeground: T3RGBA(39, 39, 42, 1.0),
        terminalSelectionBackground: T3RGBA(37, 63, 99, 0.2),
        toolErrorIcon: T3RGBA(251, 44, 54, 1.0),
        toolbarBackground: T3RGBA(252, 252, 252, 1.0),
        toolbarBorder: T3RGBA(228, 228, 231, 1.0),
        toolbarControl: T3RGBA(255, 255, 255, 1.0),
        toolbarControlForeground: T3RGBA(39, 39, 42, 1.0),
        toolbarControlHover: T3RGBA(244, 244, 245, 1.0),
        toolbarForeground: T3RGBA(39, 39, 42, 1.0),
        update: T3RGBA(27, 78, 216, 1.0),
        updateForeground: T3RGBA(27, 78, 216, 1.0),
        updateSurface: T3RGBA(27, 78, 216, 0.12),
        warning: T3RGBA(254, 154, 0, 1.0),
        warningForeground: T3RGBA(187, 77, 0, 1.0),
        warningSurface: T3RGBA(254, 154, 0, 0.08)
    )
    public static let webDark = WebPalette(
        accent: T3RGBA(255, 255, 255, 0.04),
        accentForeground: T3RGBA(245, 245, 245, 1.0),
        appChromeBackground: T3RGBA(10, 10, 10, 1.0),
        background: T3RGBA(10, 10, 10, 1.0),
        border: T3RGBA(255, 255, 255, 0.06),
        card: T3RGBA(17, 17, 17, 1.0),
        cardForeground: T3RGBA(245, 245, 245, 1.0),
        codeBackground: T3RGBA(17, 17, 17, 1.0),
        codeForeground: T3RGBA(245, 245, 245, 1.0),
        destructive: T3RGBA(251, 65, 74, 1.0),
        destructiveForeground: T3RGBA(255, 100, 103, 1.0),
        error: T3RGBA(251, 65, 74, 1.0),
        errorForeground: T3RGBA(255, 100, 103, 1.0),
        errorSurface: T3RGBA(251, 65, 74, 0.16),
        foreground: T3RGBA(245, 245, 245, 1.0),
        iconMuted: T3RGBA(129, 129, 129, 1.0),
        info: T3RGBA(43, 127, 255, 1.0),
        infoForeground: T3RGBA(81, 162, 255, 1.0),
        input: T3RGBA(255, 255, 255, 0.08),
        messageAction: T3RGBA(52, 107, 241, 1.0),
        messageActionForeground: T3RGBA(255, 255, 255, 1.0),
        messageActionHover: T3RGBA(48, 97, 218, 1.0),
        messageForeground: T3RGBA(245, 245, 245, 1.0),
        messageSurface: T3RGBA(255, 255, 255, 0.04),
        muted: T3RGBA(255, 255, 255, 0.03),
        mutedForeground: T3RGBA(129, 129, 129, 1.0),
        placeholder: T3RGBA(129, 129, 129, 1.0),
        popover: T3RGBA(17, 17, 17, 1.0),
        popoverForeground: T3RGBA(245, 245, 245, 1.0),
        primary: T3RGBA(52, 107, 241, 1.0),
        primaryForeground: T3RGBA(255, 255, 255, 1.0),
        ring: T3RGBA(52, 107, 241, 1.0),
        secondary: T3RGBA(255, 255, 255, 0.03),
        secondaryForeground: T3RGBA(245, 245, 245, 1.0),
        secondaryLabel: T3RGBA(129, 129, 129, 1.0),
        sidebar: T3RGBA(0, 0, 0, 1.0),
        sidebarBorder: T3RGBA(255, 255, 255, 0.08),
        sidebarControlSurface: T3RGBA(10, 10, 10, 1.0),
        sidebarForeground: T3RGBA(241, 243, 247, 1.0),
        sidebarMutedForeground: T3RGBA(163, 163, 163, 1.0),
        sidebarRowActive: T3RGBA(241, 243, 247, 0.11),
        sidebarRowHover: T3RGBA(241, 243, 247, 0.08),
        sidebarRowSelected: T3RGBA(241, 243, 247, 0.07),
        sidebarStageFade: T3RGBA(0, 0, 0, 1.0),
        success: T3RGBA(0, 188, 125, 1.0),
        successForeground: T3RGBA(0, 212, 146, 1.0),
        surfaceRaised: T3RGBA(17, 17, 17, 1.0),
        terminalBackground: T3RGBA(10, 10, 10, 1.0),
        terminalCursor: T3RGBA(180, 203, 255, 1.0),
        terminalForeground: T3RGBA(245, 245, 245, 1.0),
        terminalSelectionBackground: T3RGBA(180, 203, 255, 0.25),
        toolErrorIcon: T3RGBA(252, 165, 165, 1.0),
        toolbarBackground: T3RGBA(10, 10, 10, 1.0),
        toolbarBorder: T3RGBA(255, 255, 255, 0.06),
        toolbarControl: T3RGBA(17, 17, 17, 1.0),
        toolbarControlForeground: T3RGBA(245, 245, 245, 1.0),
        toolbarControlHover: T3RGBA(255, 255, 255, 0.04),
        toolbarForeground: T3RGBA(245, 245, 245, 1.0),
        update: T3RGBA(52, 107, 241, 1.0),
        updateForeground: T3RGBA(81, 162, 255, 1.0),
        updateSurface: T3RGBA(52, 107, 241, 0.18),
        warning: T3RGBA(254, 154, 0, 1.0),
        warningForeground: T3RGBA(255, 185, 0, 1.0),
        warningSurface: T3RGBA(254, 154, 0, 0.16)
    )
    public enum Metrics {
        public static let radius: Double = 10
        public static let controlRadius: Double = 8
        public static let sidebarWidth: Double = 256
        public static let sidebarWidthIcon: Double = 48
        public static let topbarHeight: Double = 52
        public static let sidebarContentInset: Double = 8
        public static let sidebarRowContentInset: Double = 10
        public static let scrollbarWidth: Double = 6
    }
}
