import Foundation
import InfinitusCore

/// Pure pairing logic and data structures for the Windows Devices settings pane.
/// Testable without WinSDK HWND handles.
public enum PairingChecklist {
    public struct Step: Equatable, Sendable {
        public let id: Int
        public let title: String
        public let detail: String
        public let done: Bool

        public init(id: Int, title: String, detail: String, done: Bool) {
            self.id = id
            self.title = title
            self.detail = detail
            self.done = done
        }
    }

    public struct RouteItem: Equatable, Sendable {
        public let id: String
        public let title: String
        public let endpoint: String

        public init(id: String, title: String, endpoint: String) {
            self.id = id
            self.title = title
            self.endpoint = endpoint
        }
    }

    public static func steps(
        serving: Bool,
        port: UInt16?,
        lastServed: Date?,
        routes: [RouteItem]
    ) -> [Step] {
        let isServing = serving && port != nil
        let remote = routes.contains { $0.id != "lan" }

        return [
            Step(
                id: 1,
                title: "1. Serve the fleet to my phone",
                detail: "The toggle below. This box answers with its session snapshot; nothing leaves the machine otherwise.",
                done: isServing
            ),
            Step(
                id: 2,
                title: "2. Put Infinitus on the phone",
                detail: "The iOS companion lives in ios/ of the repo.",
                done: lastServed != nil
            ),
            Step(
                id: 3,
                title: "3. Pick how the phone reaches this PC",
                detail: remote
                    ? "Same Wi-Fi works already; a remote route is up too."
                    : "Same Wi-Fi needs nothing. From anywhere: Tailscale on both devices.",
                done: !routes.isEmpty
            ),
            Step(
                id: 4,
                title: "4. Scan the QR from the phone",
                detail: "On the phone: Settings → Mac connection → Scan QR.",
                done: lastServed != nil
            )
        ]
    }

    public static func portChangeWarning(port: UInt16) -> String? {
        if port != 47824 {
            return "The phone's QR carries this port; a paired phone needs a fresh scan after a change."
        }
        return nil
    }

    public static func agentBrief(
        steps: [Step],
        serving: Bool,
        port: UInt16?,
        routes: [RouteItem],
        token: String?,
        revealToken: Bool,
        tailscaleAddress: String?,
        machineName: String = "this PC"
    ) -> String {
        let portStr = port.map(String.init) ?? "47824"
        let tokenStr: String
        if revealToken, let token, !token.isEmpty {
            tokenStr = token
        } else {
            tokenStr = "<hidden — in Infinitus: Settings → Devices → Pairing token → Reveal/Copy>"
        }

        var lines: [String] = [
            "# Infinitus — set up the phone companion (agent brief)",
            "Generated by Infinitus on \(machineName).",
            "Source: https://github.com/deathemperor/infinitus",
            "",
            "## State"
        ]

        for s in steps {
            lines.append("- [\(s.done ? "x" : " ")] \(s.title)")
        }
        lines.append("- Listener: \(serving ? "on, port \(portStr)" : "off")")
        for r in routes {
            lines.append("- Route \"\(r.title)\": \(r.endpoint)")
        }
        lines.append("- Pairing token: \(tokenStr)")
        if let ts = tailscaleAddress {
            lines.append("- Tailscale on this PC: connected · \(ts)")
        } else {
            lines.append("- Tailscale on this PC: not connected")
        }

        let primaryEndpoint = routes.first?.endpoint ?? "http://localhost:\(portStr)"

        lines += [
            "",
            "## Do the unticked steps, in order",
            "1. Serving: a toggle in Settings → Devices (\"Serve the fleet to my phone\").",
            "2. Phone app: the iOS companion lives in ios/ of the repo.",
            "3. Routes: Wi-Fi (LAN) / Tailscale.",
            "4. Verify listener with curl.exe:",
            "   curl.exe -s -o NUL -w \"%{http_code}\\n\" -H \"Authorization: Bearer <token>\" \(primaryEndpoint)/snapshot",
            "5. Firewall:",
            "   netsh advfirewall firewall add rule name=\"Infinitus\" dir=in action=allow protocol=TCP localport=\(portStr)"
        ]

        return lines.joined(separator: "\n")
    }
}
